version: '3.8'

services:
  evo-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: evo-server:latest
    container_name: evo-server
    ports:
      - "8080:8080"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./data:/app/data
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "evo-server"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
